#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#

left, right = [0,1]
sum = 0
max = ARGV[0] ? ARGV[0].to_i : 10

while right < max 
  sum += right if right.even?
  left, right = right,left+right
end

puts "sum: #{sum}"



